// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
// command for express js, jwt, bcrypt, cookie-parser, cors, http-status  
// npm install express jsonwebtoken bcrypt cookie-parser cors http-status
// command for only needed types 
